### ISSUE TITLE
protoc-bridge (and so sbt-protoc) does not work with Python 3 on Windows

### ISSUE THREAD

**Issue by david-mcgillicuddy-ovo** [thesamet/sbt-protoc#50] opened 2018-01-10 16:40 UTC
The error gotten when it was running with python 3 is:
```
Traceback (most recent call last):
  File "C:\Users\DMCGIL~1\AppData\Local\Temp\protocbridge7979764971266522589.py", line 6, in <module>
    s.sendall(content)
TypeError: a bytes-like object is required, not 'str'
```

The problem was solved by adding 
```
PB.pythonExe := "C:\\Python27\\python.exe"
```
to the `build.sbt` (I'm going to move it into my user .sbt file), since the default `python` in the PATH was python 3.

**Comment by thesamet** [comment] 2018-01-10 17:23
Duplicate of scalapb/ScalaPB#368

**Closed by thesamet** 2018-01-10 17:23 UTC
