### ISSUE TITLE
Migrating out of Bintray

### ISSUE THREAD

**Issue by alpex92** [thesamet/sbt-protoc#240] opened 2021-04-12 17:08 UTC
Bintray is scheduled to shut down at may 1st and currently not available at 12 april (service brown-outs to remind users about the services that are going away on May 1st.)

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/ 

artifacts would not be available leading to CI/CD and fresh project failures

consider publishing artifacts somewhere else

**Comment by thesamet** [comment] 2021-04-12 17:15
Duplicate of #236.

**Closed by thesamet** 2021-04-12 17:15 UTC
