### ISSUE TITLE
Add support for Apple M1

### ISSUE THREAD

**Issue by wangjia184** [thesamet/sbt-protoc#235] opened 2021-03-13 02:32 UTC
I tried both version 0.99 and 1.0

Also I tried to configure local protoc
```
// Use a locally provided protoc (in 1.x):
PB.protocExecutable := file("/Users/jerry/protoc-3.11.4-osx-aarch_64.exe")

// For sbt-protoc < 1.0 only:
PB.runProtoc := (args => Process("/Users/jerry/protoc-3.11.4-osx-aarch_64.exe", args)!)
```

Can it be fixed?

```
[error] java.lang.RuntimeException: error occurred while compiling protobuf files: Unsupported platform: protoc-3.11.4-osx-aarch_64.exe
[error] 	at sbtprotoc.ProtocPlugin$.executeProtoc(ProtocPlugin.scala:293)
[error] 	at sbtprotoc.ProtocPlugin$.compile(ProtocPlugin.scala:341)
[error] 	at sbtprotoc.ProtocPlugin$.compileProto$1(ProtocPlugin.scala:431)
[error] 	at sbtprotoc.ProtocPlugin$.$anonfun$sourceGeneratorTask$10(ProtocPlugin.scala:438)
[error] 	at sbt.util.FileFunction$.$anonfun$cached$1(FileFunction.scala:73)
[error] 	at sbt.util.FileFunction$.$anonfun$cached$4(FileFunction.scala:146)
[error] 	at sbt.util.Difference.apply(Tracked.scala:323)
[error] 	at sbt.util.Difference.apply(Tracked.scala:303)
[error] 	at sbt.util.FileFunction$.$anonfun$cached$3(FileFunction.scala:142)
[error] 	at sbt.util.Difference.apply(Tracked.scala:323)
[error] 	at sbt.util.Difference.apply(Tracked.scala:298)
[error] 	at sbt.util.FileFunction$.$anonfun$cached$2(FileFunction.scala:141)
[error] 	at sbtprotoc.ProtocPlugin$.$anonfun$sourceGeneratorTask$4(ProtocPlugin.scala:443)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[error] 	at java.base/java.lang.Thread.run(Thread.java:831)
```

Neither works on Mac OS M1 ARM64

**Comment by thesamet** [comment] 2021-03-13 05:19
Closing as duplicate of scalapb/ScalaPB/issues/1024

**Comment by thesamet** [comment] 2021-03-13 06:34
Re-opening since a locally provided protoc should work. Given the error message you are seeing, it looks like `PB.protocExecutable` is being ignored. Can you provide a full build.sbt?

**Comment by wangjia184** [comment] 2021-03-15 06:16
Hi @thesamet 
build.sbt file is basing on here: https://github.com/rchain/rchain/blob/dev/build.sbt

but I tried the following code and it does not work, although they are not commited 
```
// Use a locally provided protoc (in 1.x):
PB.protocExecutable := file("/Users/jerry/protoc-3.11.4-osx-aarch_64.exe")

// For sbt-protoc < 1.0 only:
PB.runProtoc := (args => Process("/Users/jerry/protoc-3.11.4-osx-aarch_64.exe", args)!)
```

**Comment by thesamet** [comment] 2021-03-15 06:22
@wangjia184 - let's try making it work on a sample project first. Can you try

```
sbt new scalapb/scalapb-template.g8
```

and then make the modifications in build.sbt?

**Comment by thesamet** [comment] 2021-04-16 03:25
Closing due to inactivity. I believe a locally compiled protoc should work.

**Closed by thesamet** 2021-04-16 03:25 UTC
