### ISSUE TITLE
protoc-gen-jvm

### ISSUE THREAD

**Issue by PaddleWang** [thesamet/sbt-protoc#96] opened 2019-08-24 02:47 UTC
When I tried to execute this command
```
[C:\Users\26804\AppData\Local\Temp\protocjar5737050678362154077\bin\protoc.exe, --plugin=protoc-gen-jvm_hiyB4lbG=C:\Users\26804\AppData\Local\Temp\protocbridge1055682509143521741.bat, --plugin=protoc-gen-jvm_mUHPcxV5=C:\Users\26804\AppData\Local\Temp\protocbridge4757607570199059927.bat, --plugin=protoc-gen-jvm_u96mpbJk=C:\Users\26804\AppData\Local\Temp\protocbridge4637337314990832430.bat, --java_out=:E:\WebLearning\agent-center\models\model-base\target\scala-2.12\src_managed\main, --jvm_hiyB4lbG_out=:E:\WebLearning\agent-center\models\model-base\target\scala-2.12\src_managed\main, --jvm_mUHPcxV5_out=:E:\WebLearning\agent-center\models\model-base\target\scala-2.12\src_managed\main, --jvm_u96mpbJk_out=:E:\WebLearning\agent-center\models\model-base\target\scala-2.12\src_managed\main, -IE:\WebLearning\agent-center\models\model-base\src\main\protobuf, -IE:\WebLearning\agent-center\models\model-base\target\protobuf_external, -IE:\WebLearning\agent-center\models\model-base\src\main\protobuf, -IE:\WebLearning\agent-center\models\model-base\target\protobuf_external, E:\WebLearning\agent-center\models\model-base\src\main\protobuf\Enums.proto, E:\WebLearning\agent-center\models\model-base\src\main\protobuf\FePermission.proto, E:\WebLearning\agent-center\models\model-base\src\main\protobuf\Messages.proto, E:\WebLearning\agent-center\models\model-base\src\main\protobuf\Perms.proto
```
SocketException was thrown but I thought the "protoc.exe" was not problem
```
Exception in thread "main" java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:210)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at java.net.SocketInputStream.read(SocketInputStream.java:127)
        at protocbridge.frontend.BridgeApp.readInputStreamToByteArray(BridgeApp.java:30)
        at protocbridge.frontend.BridgeApp.main(BridgeApp.java:21)
--jvm_hiyB4lbG_out: protoc-gen-jvm_hiyB4lbG: Plugin failed with status code 1.
[error] java.lang.RuntimeException: protoc returned exit code: 1
[error]         at scala.sys.package$.error(package.scala:26)
[error]         at sbtprotoc.ProtocPlugin$.compile(ProtocPlugin.scala:142)
[error]         at sbtprotoc.ProtocPlugin$.compileProto$1(ProtocPlugin.scala:182)
[error]         at sbtprotoc.ProtocPlugin$.$anonfun$sourceGeneratorTask$4(ProtocPlugin.scala:186)
[error]         at sbt.util.FileFunction$.$anonfun$cached$1(FileFunction.scala:73)
[error]         at sbt.util.FileFunction$.$anonfun$cached$4(FileFunction.scala:147)
[error]         at sbt.util.Difference.apply(Tracked.scala:313)
[error]         at sbt.util.Difference.apply(Tracked.scala:293)
[error]         at sbt.util.FileFunction$.$anonfun$cached$3(FileFunction.scala:143)
[error]         at sbt.util.Difference.apply(Tracked.scala:313)
[error]         at sbt.util.Difference.apply(Tracked.scala:288)
[error]         at sbt.util.FileFunction$.$anonfun$cached$2(FileFunction.scala:142)
[error]         at sbtprotoc.ProtocPlugin$.$anonfun$sourceGeneratorTask$1(ProtocPlugin.scala:192)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (model-base / Compile / protocGenerate) protoc returned exit code: 1
```

**Comment by thesamet** [comment] 2019-08-24 02:58
Looks like you're invoking multiple JVM plugins simultaneously and the error says that one of the plugins exits with an error. Without knowing what these plugin(s) are and how you are invoking them it's hard to help you further. Can you provide an example I can reproduce locally?

**Comment by PaddleWang** [comment] 2019-08-24 03:04
> Looks like you're invoking multiple JVM plugins simultaneously and the error says that one of the plugins exits with an error. Without knowing what these plugin(s) are and how you are invoking them it's hard to help you further. Can you provide an example I can reproduce locally?

Thanks for your reply. 
```
# There is a model-base package in project and its owner made a defination like this
# build.sbt
lazy val `model-base` = (project in file("./models/model-base"))
  .enablePlugins(PlayEbean)
  .settings(
    name := "model-base",
    modelSettings,
    PB.protocVersion := "-v360",
    PB.targets in Compile := Seq(
      PB.gens.java -> (sourceManaged in Compile).value,
      //      scalapb.gen(javaConversions = true, grpc = false) -> (sourceManaged in Compile).value,
      PbConverterGenerator.attributeConverter -> (sourceManaged in Compile).value,
      PermissionGenerator.permConverter(file("./web-fe/src")) -> (sourceManaged in Compile).value,
      FePermissionGenerator.permConverter(file("./web-fe/src")) -> (sourceManaged in Compile).value,
    ),
    libraryDependencies ++= Seq(
      "com.google.protobuf" % "protobuf-java" % "3.6.0" % "compile,protobuf",
      "com.thesamet.scalapb" %% "scalapb-runtime" % "0.8.4" % "compile,protobuf",
      "io.ebean" % "persistence-api" % "2.2.1",
      "gdt.proto" % "proto-ad" % "1.0.123",
      "org.apache.commons" % "commons-lang3" % "3.9",
    ),
    dependencyOverrides ++= Seq(
      "com.google.protobuf" % "protobuf-java" % "3.6.0"
    ),
  )
# plugins.sbt 
addSbtPlugin("com.thesamet" % "sbt-protoc" % "0.99.18")
libraryDependencies += "com.thesamet.scalapb" %% "compilerplugin" % "0.9.0"
```

**Comment by PaddleWang** [comment] 2019-08-24 03:05
And...should I hand in my proto model?

**Comment by thesamet** [comment] 2019-08-24 03:25
@PaddleWang The error is coming from one of the plugins you are invoking `PbConverterGenerator.attributeConverter`, `PermissionGenerator.permConverter`, or `FePermissionGenerator.permConverter`. One of these plugins is throwing an exception instead of providing an error message. Those plugins are non-standard and it's unclear where you obtained them from so I will be unable to reproduce this problem on my computer even if you provide your proto models. Ideally, you can create a minimal github repo with everything that is necessary to demonstrate this problem.

**Comment by thesamet** [comment] 2019-09-14 23:04
Closing for now. Please feel free to re-open if the issue is still relevant.

**Closed by thesamet** 2019-09-14 23:04 UTC
Labels: more-info-needed, question
