### ISSUE TITLE
deserialized old messages have `null` for new Optional field

### ISSUE THREAD

**Issue by retrospectacus** [thesamet/sbt-protoc#79] opened 2019-02-13 23:27 UTC
Steps to help produce issue;

1. create a simple message with a few fields.
```
message Answer {
    int32 number = 1;
    string text = 2;
}
```
2. Persist one or more of these messages.
3. Add an optional string to the message definition.
```
message Answer {
    int32 number = 1;
    string text = 2;
    google.protobuf.StringValue user_id = 3;
}
```
4. The generated case class has `userId: Option[String] = None`; great.
5. Deserialize and print the messages stored in step 2.

Expected result:
`Answer(1, test, None)`

Actual result:
`Answer(1, test, null)`

This causes unexpected bugs (Null Pointer Exceptions) after system upgrades / migrations.
They can be handled by something like `Option(answer.userId).flatten` but...
This is Scala; we do not like `null`!

**Comment by thesamet** [comment] 2019-02-13 23:37
This is definitely not the intended behavior, you should not be seeing `null`s. How do you serialize and deserialize?

One way to test the behavior in a single program is to create two messages, one with the new field and one without. Then serialize using the first message and deserialize using the second, that eliminates the need to change and recompile.

**Comment by retrospectacus** [comment] 2019-02-13 23:48
This system is using Akka Persistence journal to log events.
It is using the default Java serializer.

**Comment by thesamet** [comment] 2019-02-13 23:54
That's not a ScalaPB bug then, since the class instantiation during deserialization happens outside of ScalaPB's control. Find a way to serialize and deserialize using ScalaPB methods (`toByteArray` and `parseFrom`) and you wouldn't be seeing those nulls. Will be closing this ticket, but doesn't hesitate to reach out for questions or further help on the ScalaPB github project or on our gitter channel.

**Closed by thesamet** 2019-02-13 23:54 UTC

**Comment by retrospectacus** [comment] 2019-02-14 00:27
Thank you. It works when I configure Akka persistence to use a custom serializer, implemented using `GeneratedMessage.toByteArray` and `parseFrom`.
